language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm-nightly

sudo: false

before_install:    
  - composer self-update
  
install:  
  - travis_retry composer install --no-interaction --prefer-source
  - bin/phing dist

script:
  - bin/phpunit --bootstrap "./vendor/autoload.php" --coverage-text --coverage-clover=coverage.clover
  - bin/phpcs 

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
